# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBgAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topmenu', models.IntegerField()),
                ('act', models.IntegerField()),
                ('adv', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileBgAdUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('html', models.TextField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_bg.MobileBgAd')),
            ],
        ),
        migrations.AddField(
            model_name='mobilebgad',
            name='last_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_bg.MobileBgAdUpdate'),
        ),
    ]
