# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
