# Generated by Django 2.0 on 2017-12-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0002_mobilebgad_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='first_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_update_ads', to='mobile_bg.MobileBgAdUpdate'),
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilebgad',
            name='last_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_update_ads', to='mobile_bg.MobileBgAdUpdate'),
        ),
    ]
