# Generated by Django 2.0 on 2017-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0004_auto_20171213_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebgad',
            name='active',
        ),
    ]
