# Generated by Django 2.0 on 2017-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0005_remove_mobilebgad_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
