# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0006_mobilebgad_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='last_price_drop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_price_drop_ads', to='mobile_bg.MobileBgAdUpdate'),
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='prev_update',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_update', to='mobile_bg.MobileBgAdUpdate'),
        ),
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='mobile_bg.MobileBgAd'),
        ),
    ]
