# Generated by Django 2.0 on 2017-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0010_mobilebgadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadimage',
            name='big_url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilebgadimage',
            name='small_url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
