# Generated by Django 2.0 on 2017-12-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0011_auto_20171222_1346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilebgadimage',
            unique_together={('ad', 'index')},
        ),
    ]
