# Generated by Django 2.0 on 2017-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0012_auto_20171222_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='price_currency',
            field=models.IntegerField(blank=True, choices=[(0, 'BGN'), (1, 'EUR')], null=True),
        ),
    ]
