# Generated by Django 2.0 on 2017-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0013_mobilebgadupdate_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBgScrapeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slink', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
