# Generated by Django 2.0 on 2017-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0017_auto_20171227_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='last_update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
