# Generated by Django 2.0 on 2017-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0019_mobilebgadupdate_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='engine_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Petrol'), (1, 'Diesel'), (2, 'Hybrid'), (3, 'Electric')], null=True),
        ),
    ]
