# Generated by Django 2.0 on 2017-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0020_mobilebgadupdate_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='mileage_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
