# Generated by Django 2.0 on 2017-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0021_mobilebgadupdate_mileage_km'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilebgscrapelink',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='power_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebgscrapelink',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
