# Generated by Django 2.0 on 2017-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0022_auto_20171228_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgad',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='price_currency',
            field=models.IntegerField(blank=True, choices=[(0, 'BGN'), (1, 'EUR'), (2, 'USD')], null=True),
        ),
    ]
