# Generated by Django 2.0 on 2017-12-29 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0023_auto_20171229_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
