# Generated by Django 2.0 on 2017-12-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0024_auto_20171229_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='ad_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
