# Generated by Django 2.0 on 2017-12-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0025_mobilebgscrapelink_ad_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='last_full_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_full_update_ads', to='mobile_bg.MobileBgAdUpdate'),
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Full'), (1, 'Price Only')], default=0),
        ),
    ]
