# Generated by Django 2.0 on 2018-01-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0026_auto_20171231_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
