# Generated by Django 2.0 on 2018-01-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0027_auto_20180101_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilebgscrapelink',
            options={'ordering': ('name', 'max_price')},
        ),
    ]
