# Generated by Django 2.0.1 on 2018-01-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0028_auto_20180101_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebgad',
            name='act',
        ),
    ]
