# Generated by Django 2.0.1 on 2018-01-02 14:26

from django.db import migrations, models
import mobile_bg.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0029_remove_mobilebgad_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgadimage',
            name='image_big',
            field=models.FileField(upload_to=mobile_bg.models._image_big_upload_to),
        ),
        migrations.AlterField(
            model_name='mobilebgadimage',
            name='image_small',
            field=models.FileField(upload_to=mobile_bg.models._image_small_upload_to),
        ),
    ]
