# Generated by Django 2.0 on 2018-01-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0030_auto_20180102_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebgadimage',
            name='image_small',
        ),
    ]
