# Generated by Django 2.0.1 on 2018-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0031_remove_mobilebgadimage_image_small'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilebgadupdate',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='transmission_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Manual'), (1, 'Automatic'), (2, 'Semiautomatic')], null=True),
        ),
    ]
