# Generated by Django 2.0.1 on 2018-01-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0032_auto_20180105_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='html_checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='html_delta',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='html_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
