# Generated by Django 2.0.1 on 2018-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0033_auto_20180105_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='html_checksum',
            field=models.CharField(max_length=32),
        ),
    ]
