# Generated by Django 2.0.1 on 2018-01-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0034_auto_20180105_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgad',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Кола'), (2, 'Джип'), (3, 'Бус'), (4, 'Камион'), (5, 'Мотор'), (6, 'Селскостопански'), (7, 'Индустриален'), (8, 'Кар'), (9, 'Караван')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Кола'), (2, 'Джип'), (3, 'Бус'), (4, 'Камион'), (5, 'Мотор'), (6, 'Селскостопански'), (7, 'Индустриален'), (8, 'Кар'), (9, 'Караван')], default=1),
            preserve_default=False,
        ),
    ]
