# Generated by Django 2.0.1 on 2018-01-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0036_auto_20180105_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
