# Generated by Django 2.0.1 on 2018-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0037_mobilebgadupdate_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='body_style',
            field=models.IntegerField(blank=True, choices=[(101, 'Ван'), (102, 'Кабрио'), (103, 'Комби'), (104, 'Купе'), (105, 'Миниван'), (106, 'Пикап'), (107, 'Седан'), (108, 'Стреч лимузина'), (109, 'Хечбек'), (201, 'Къса база'), (202, 'Дълга база'), (203, 'Пикап - Къса база'), (204, 'Пикап - Дълга база')], null=True),
        ),
    ]
