# Generated by Django 2.0.1 on 2018-01-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0038_mobilebgadupdate_body_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='location_city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='location_region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
