# Generated by Django 2.0.1 on 2018-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0040_auto_20180106_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadupdate',
            name='seller_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
