# Generated by Django 2.0.1 on 2018-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0043_auto_20180107_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadimage',
            name='photo_object',
            field=models.IntegerField(choices=[(1, 'Екстериор'), (2, 'Интериор'), (3, 'Двигател'), (4, 'Друго')], null=True),
        ),
    ]
