# Generated by Django 2.0.1 on 2018-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0045_mobilebgadimage_photo_object_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgadimage',
            name='photo_object',
            field=models.IntegerField(choices=[(1, 'Екстериор'), (2, 'Интериор'), (3, 'Двигател'), (4, 'Друго')], db_index=True, null=True),
        ),
    ]
