# Generated by Django 2.0.1 on 2018-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0046_auto_20180112_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebgadimage',
            name='photo_object_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
