# Generated by Django 2.0.1 on 2018-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0047_auto_20180112_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgscrapelink',
            name='slink_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilebgadupdate',
            name='transmission_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Ръчни'), (1, 'Автоматик'), (2, 'Полуавтоматик')], null=True),
        ),
    ]
