# Generated by Django 2.0.1 on 2018-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_bg', '0048_auto_20180115_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebgadimage',
            name='photo_object_pred',
            field=models.IntegerField(choices=[(1, 'Екстериор'), (2, 'Интериор'), (3, 'Двигател'), (4, 'Друго')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilebgadimage',
            name='photo_object_pred_v',
            field=models.IntegerField(null=True),
        ),
    ]
